"""
SahayakMap — EOC PDF Export (Task 9)
=====================================
Generates timestamp-locked PDF reports for SOS events.
Immutable after generation — audit trail for EOC justification.

Usage:
    python pdf_export.py SOS-2026-MAH-001 Naraj
"""

import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path

import requests
from fpdf import FPDF

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("SahayakMap.PDF")

EXPORTS_DIR = Path("exports")
EXPORTS_DIR.mkdir(exist_ok=True)

VPS_STATIONS = "https://www.joodei.org/sahayak-data/data/stations"
VPS_CHART   = "https://www.joodei.org/sahayak-data/data/chart"
TELEGRAM_STATE = "https://www.joodei.org/api/telegram/state"
LOCAL_SOS   = "http://localhost:5000/api/sos"
LOCAL_ALERTS = "http://localhost:5000/api/alerts"


def fetch_json(url: str) -> dict:
    try:
        return requests.get(url, timeout=15).json()
    except Exception:
        return {}


def _safe(text):
    return str(text).replace("—", "-").replace("\u2013", "-").replace("\u2014", "-")
    """Generate PDF report for an SOS event. Returns file path."""
    now = datetime.now(timezone.utc)
    ts_label = now.strftime("%Y-%m-%d %H:%M UTC")
    filename = f"sos_{event_id}_{now.strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = EXPORTS_DIR / filename

    # Fetch data
    stations = fetch_json(VPS_STATIONS)
    st = next((s for s in stations if s["name"] == station), {})
    sos = fetch_json(f"{LOCAL_SOS}/{station}")
    alerts = fetch_json(LOCAL_ALERTS)
    telegram = fetch_json(TELEGRAM_STATE)

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    def t(text):
        return str(text).replace("\u2014", "-").replace("\u2013", "-")

    # ── Header ──
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "SAHAYAKMAP — EOC JUSTIFICATION REPORT", align="C")
    pdf.ln(12)

    # ── Incident ID + Timestamp ──
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, f"Incident ID: {event_id}", align="L")
    pdf.ln(7)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Generated: {ts_label} | This report is immutable after generation", align="L")
    pdf.ln(10)

    # ── Station Telemetry ──
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, _safe(f"Station: {st.get('name', station)} — {st.get('river', '')} / {st.get('district', '')}"), align="L")
    pdf.ln(8)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"WSE: {st.get('latest_wse', 'N/A')}m | Warning: {st.get('warning_level', 'N/A')}m | Danger: {st.get('danger_level', 'N/A')}m | HFL: {st.get('hfl', 'N/A')}m", align="L")
    pdf.ln(10)

    # ── SOS Intelligence ──
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "SOS Intelligence")
    pdf.ln(8)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Forecast +8h: {sos.get('forecast_8h', 'N/A')}m | Upper CI: {sos.get('forecast_upper_ci', 'N/A')}m", align="L")
    pdf.ln(6)
    pdf.cell(0, 6, f"Evacuate Window: {sos.get('evacuate_window', 'N/A')} | Rise Rate: {sos.get('rise_rate_mph', 'N/A')} m/hr", align="L")
    pdf.ln(6)
    pdf.cell(0, 6, f"Route Risk: {sos.get('route_risk', 'N/A')} ({sos.get('route_risk_level', 'N/A')})", align="L")
    pdf.ln(6)
    pdf.cell(0, 6, f"Nearest Safe Zone: {sos.get('nearest_safe_zone', 'N/A')}", align="L")
    pdf.ln(10)

    # ── Nearest Boats ──
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Nearest Boats Dispatched")
    pdf.ln(8)
    pdf.set_font("Helvetica", "", 10)
    boats = sos.get("nearest_boats", [])
    if boats:
        for b in boats:
            pdf.cell(0, 6, f"  {b['call_sign']} ({b['team_id']}) — {b['distance_km']}km | {b['district']} | {b['status']}", align="L")
            pdf.ln(5)
    else:
        pdf.cell(0, 6, "  No boats available", align="L")
    pdf.ln(5)

    # ── Team Positions ──
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Team Positions (Last Telegram Pings)")
    pdf.ln(8)
    pdf.set_font("Helvetica", "", 10)
    teams = telegram.get("responses", {})
    if teams:
        for t, r in teams.items():
            pdf.cell(0, 6, f"  {t}: {r.get('status', 'N/A')} | {r.get('location', 'N/A')} | {r.get('time', 'N/A')[:19]}", align="L")
            pdf.ln(5)
    else:
        pdf.cell(0, 6, "  No team data available", align="L")
    pdf.ln(10)

    # ── Active Alerts ──
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, f"Active Alerts ({len(alerts)} total)")
    pdf.ln(8)
    pdf.set_font("Helvetica", "", 9)
    for a in alerts[:5]:
        pdf.cell(0, 5, f"  [{a.get('rule_id', '?')}] {a.get('title', 'N/A')[:80]}", align="L")
        pdf.ln(4)

    pdf.ln(10)

    # ── Signature ──
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 6, f"Generated by SahayakMap | {ts_label} | Event ID: {event_id}", align="C")
    pdf.ln(4)
    pdf.cell(0, 6, "This document is an automated flood intelligence report. Timestamps are locked at generation time.", align="C")

    pdf.output(str(filepath))
    log.info("PDF generated: %s", filepath)
    return str(filepath)


if __name__ == "__main__":
    import sys
    eid = sys.argv[1] if len(sys.argv) > 1 else "SOS-2026-MAH-001"
    station = sys.argv[2] if len(sys.argv) > 2 else "Naraj"
    path = generate(eid, station)
    print(path)
